### ISSUE TITLE
Http failure response for https://js7.xxx.xxx/joc/api/events: 504 Gateway Time-out

### ISSUE THREAD

**Issue by r0mingo** [sos-berlin/joc-cockpit#16]
Hello, I have an issue with the cockpit of JS7. When we are logged in, sometimes we have this error : 
![image](https://github.com/sos-berlin/joc-cockpit/assets/29710370/78c91e98-150e-408e-ab32-65c1519fdc54)

Our config (everything on the same server): 
- JOC (2.4.1) in Docker container
- Controller (2.4.1) in Docker container
- Haproxy (not in container)

**Comment by sosap** [comment]
Sorry for the late reply. Most probably your HAProxy is configured for a gateway timeout of idle connections below 55s. This is the period for which the JOC Cockpit GUI waits for events of the JS7 REST Web Service API that are used to update the GUI. If the timeout is exceeded then the request is completed and a new request is created.

To our knowledge 60s is a frequently used default value for proxy gateway timeout settings.

**Comment by r0mingo** [comment]
Hello, thank you very much, it's working with 65s timeout 👍
