### ISSUE TITLE
agent import not working

### ISSUE THREAD

**Issue by rfx77** [sos-berlin/joc-cockpit#22]
In Mange Controllers/Agents the item "Import Agent Configuration" is not working.

The dropdown File-Type shows emtpy items. zips or jsons cannot be dropped and when using the file-selection upload of json is not working.

Upload of a zip is allowed but the agent is not imported.

Version. 2.6.1 (Latest UI Patch)

**Comment by sosap** [comment]
The issue is confirmed and is tracked with

* [JOC-1593: Dialog for Agent import should allow to select the import archive file type](https://change.sos-berlin.com/browse/JOC-1593)

The fix will become available with releases 2.5.5 and 2.6.2
