### ISSUE TITLE
Order Overview  and Dashboard not selecting correct date

### ISSUE THREAD

**Issue by rfx77** [sos-berlin/joc-cockpit#23]
On the dashboard and the order-overview the date selection does not work.

It is 2023-08-10. and no orders or jobs failed today

Version 2.6.1 with latest UI Patch

This is the dashboard and below is the orders overview

![image](https://github.com/sos-berlin/joc-cockpit/assets/61699304/fffb4527-6ebd-43e2-a341-85fb56663481)

![image](https://github.com/sos-berlin/joc-cockpit/assets/61699304/b6d4b1bd-357e-4912-894e-967a6d16d21d)

**Comment by rfx77** [comment]
Sorry. The Orders where not Canceled.

**Comment by sosap** [comment]
This works as designed. The Dashboard offers to specify a date range for scheduled orders. Any other order states are displayed independent from the date range. If you find failed, blocked or prompting orders then all of them require attention independent from the point in time of state transition.

As from your observation cancelled orders leave the workflow and are no longer indicated by the Dashboard's Order Summary widget, but are included with the Order History widget.
