### ISSUE TITLE
Cockpit doesn't allow the user to save "Credential Key" without "Load User Profile" checked in Job Options

### ISSUE THREAD

**Issue by adamlibusa** [sos-berlin/joc-cockpit#25]
## Describe the bug

In Job Options (_Open Cockpit > Configuration > Controllers > Workflows > Open a workflow GUI editor > Select a job > Click on "More Options" in the site's header > Click on the 2nd tab of job properties (Job Options)_), after filling in `Credential Key` field and not checking `Load User Profile` and clicking on `Deploy` button, the user gets a red error popup with the text `BadRequestError: JSON DecodingFailure at ... withUserProfile: Missing required field.` and the job doesn't get deployed.

This behaviour doesn't manifest itself, if also `Load User Profile` checkbox is checked. In this case, the job gets deployed and no alert is shown.

## To Reproduce

1) Create a workflow and a job

2) Fill in field "Credential Key" in Job Options (accessible via activating the toggle "More Options")

3) Do not check the "Load User Profile".

4) Click on "Deploy"

After a while, the alert appears.

## Expected behavior
JOC cockpit allows the user to deploy a job with `Credential Key` filled out & without `Load User Profile` checked, without any errors.

## Screenshots/Video
![cockpit-load-user-profile-error](https://github.com/sos-berlin/joc-cockpit/assets/1161394/c738a5ce-2b20-481d-9b6b-306c688986c1)

## Environment
 - JOC cockpit version: 2.6.3 (2023-11-13)
 - OS: Windows Server 2022 Datacenter
 - OS Version: 21H2
 - OS Installed on: 20.11.2023
 - System type: 64-bit OS, x64 processor
 - OS build: 20348.2159
 - Type of machine: Virtual Machine
 - JS7 license: SOS Berlin Commercial
 - Browser: MS Edge 119.0.2151.44 (Official build) (64-bit)

## Log entries

These are probably relevant JOC entries (the sensitive information was replaced by "..."):

> 2024-01-08T16:41:27,305 TRACE JControllerProxy-35  c.s.j.p.u.StoreDeployments                   - {"TYPE":"Workflow","path":"AdvMedia","versionId":"fd1426cb-f434-4177-a6cb-09ae2d11b7de","timeZone":"...","orderPreparation":{"parameters":{"js7Workflow.path":{"type":"String","final":"\"/AdvMedia\""}}},"instructions":[{"TYPE":"Execute.Named","jobName":"call-ssis-package","label":"call-ssis-package"},{"TYPE":"Execute.Named","jobName":"sftp-ftp-dmz","label":"sftp-ftp-dmz"}],"jobs":{"call-ssis-package":{"agentPath":"Primary","executable":{"TYPE":"ShellScriptExecutable","script":"...","login":{"credentialKey":"bbb"}},"processLimit":1,"sigkillDelay":1},"sftp-ftp-dmz":{"agentPath":"Primary","executable":{"TYPE":"ShellScriptExecutable","script":"..."},"processLimit":1,"sigkillDelay":1,"jobResourcePaths":["sftp-resource"]}}}
> 
> 2024-01-08T16:41:27,308 DEBUG JControllerProxy-35  c.s.c.h.SOSHibernateSession                  - [./inventory/deployment/deploy][update]DBItemDeploymentHistory[id=64,account=root,path=/AdvMedia,name=AdvMedia,title=<null>,folder=/,type=1,inventoryConfigurationId=5,controllerInstanceId=0,controllerId=controller,content={"TYPE":"Workflow","path":"AdvMedia","versionId":"fd1426cb-f434-4177-a6cb-09ae2d11b7de","timeZone":"...","orderPreparation":{"parameters":{"js7Workflow.path":{"type":"String","final":"\"/AdvMedia\""}}},"instructions":[{"TYPE":"Execute.Named","jo<truncated>,invContent={"TYPE":"Workflow","version":"1.6.3","timeZone":"...","instructions":[{"TYPE":"Execute.Named","jobName":"call-ssis-package","label":"call-ssis-package"},{"TYPE":"Execute.Named","jobName":"sftp-ftp-dmz","label":"sftp-ftp-dmz"}],"jobs":{"call-ssis<truncated>,updateableContent=<null>,signedContent...,commitId=fd1426cb-f434-4177-a6cb-09ae2d11b7de,version=<null>,operation=0,state=1,errorMessage=JSON DecodingFailure at .jobs.call-ssis-package.executable.withUserProfile: Missing required field,deploymentDate=2024-01-08 15:41:27,deleteDate=<null>,auditlogId=583,workflowCount=0,lockCount=0,fosCount=0,jobResourceCount=0,boardCount=0]
> 
> (some entries omitted)
> 
> 2024-01-08T16:41:27,325 ERROR JControllerProxy-35  c.s.j.c.ProblemHelper                        - BadRequestError: JSON DecodingFailure at .jobs.call-ssis-package.executable.withUserProfile: Missing required field
> 2024-01-08T16:41:27,325 TRACE JControllerProxy-35  c.s.c.h.SOSHibernateSession                  - [./inventory/deployment/deploy][close]
> 2024-01-08T16:41:27,325 DEBUG JControllerProxy-35  c.s.c.h.SOSHibernateSession                  - [./inventory/deployment/deploy][closeTransaction][rollback]NOT_ACTIVE
> 2024-01-08T16:41:27,325 DEBUG JControllerProxy-35  c.s.c.h.SOSHibernateSession                  - [./inventory/deployment/deploy][closeSession]
> 2024-01-08T16:41:27,349 DEBUG Thread-EventBus-1    c.s.j.c.e.EventService                       - add event for controller: com.sos.joc.model.event.EventSnapshot@12744b6b[path=<null>,eventId=1704728487,eventType=ProblemEvent,objectType=PROBLEM,workflow=<null>,accessToken=***,message=BadRequestError: JSON DecodingFailure at .jobs.call-ssis-package.executable.withUserProfile: Missing required field]
> 2024-01-08T16:41:28,536 DEBUG qtp85445963-19       c.s.j.c.e.EventServiceFactory                - Events for controller: [com.sos.joc.model.event.EventSnapshot@6074b103[path=/,eventId=1704728486,eventType=InventoryUpdated,objectType=FOLDER,workflow=<null>,accessToken=***,message=<null>], com.sos.joc.model.event.EventSnapshot@12744b6b[path=<null>,eventId=1704728486,eventType=ProblemEvent,objectType=PROBLEM,workflow=<null>,accessToken=***,message=BadRequestError: JSON DecodingFailure at .jobs.call-ssis-package.executable.withUserProfile: Missing required field]]

## Additional context
I am not sure if the error originates in the frontend or backend, but the HTTP requests during the deployment attempts (requests to `/joc/api/inventory/deployment/deploy` and `/joc/api/inventory/read/folder`) all return 2XX responses.

According to the logs, the problem might have originated in `sos-webservices`, but could also be connected to an issue in frontend. Therefore, I am reporting it here in frontend repository.

My hunch is that the field `withUserProfile` is marked as required in the backend & not marked as required in the frontend. Thus, the frontend doesn't send it (based on the 1st log entry) and the backend complains.

**Comment by sosap** [comment]
The issue is confirmed and is tracked by

[JOC-1715: Workflows cannot be deployed if a "Credential Key" is used without "Load User Profile"](https://change.sos-berlin.com/browse/JOC-1715)

The fix will become available with releases 2.5.8 and 2.6.5.
.
A patch for releases 2.5.7 and 2.6.4 is available for download from the above issue link.

**Comment by sosap** [comment]
Issue closed

**Comment by adamlibusa** [comment]
Thank you

**Comment by adamlibusa** [comment]
Dear SOS Berlin team. Thanks again for addressing the bug so quickly. Unfortunately, upon a clean install of the new JS7 version 2.6.4., I encountered the same behaviour. Can you check, please?

**Comment by sosap** [comment]
If you reinstall JOC Cockpit 2.6.4 then all patches are automatically removed. You therefore have to re-install the patch.

Starting from JOC Cockpit release 2.6.5 the fix will be included.

**Comment by adamlibusa** [comment]
I misunderstood the patch numbering scheme—I thought applying the patch bumps the JS7 minor version number and I was trying to apply the patch for 2.6.4 to JS7 with version 2.6.3. I successfully applied the patch to the clean installation with version 2.6.4. and I could deploy a workflow without "Load User Profile" checked.

Thank you for a quick response.
